AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SkillId:
    Type: String
  LambdaRuntime:
    Type: String
  LambdaHandler:
    Type: String
  CodeBucket:
    Type: String
  CodeKey:
    Type: String
  CodeVersion:
    Type: String
Resources:
  AlexaSkillIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: alexaSkillExecutionPolicy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - logs:*
                    - S3:*
                  Resource: "*"
  S3UserDataBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  S3WebAppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
  S3OriginAccessID:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: Origin Access Identity for S3.
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3WebAppBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - S3OriginAccessID
                  - S3CanonicalUserId
            Resource:
              - Fn::GetAtt:
                  - S3WebAppBucket
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - S3WebAppBucket
                        - Arn
                    - /*
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - S3OriginAccessID
                  - S3CanonicalUserId
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - S3WebAppBucket
                      - Arn
                  - /*
  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
          TargetOriginId: WebAppCloudfrontDistribution
          ViewerProtocolPolicy: https-only
          ForwardedValues:
            QueryString: false
        Enabled: true
        Origins:
          - DomainName: !GetAtt [S3WebAppBucket, DomainName]
            S3OriginConfig : 
              OriginAccessIdentity: !Sub
                - origin-access-identity/cloudfront/${originAccessParam}
                - originAccessParam: !Ref S3OriginAccessID
            Id: WebAppCloudfrontDistribution
  AlexaSkillFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: !Ref CodeKey
        S3ObjectVersion: !Ref CodeVersion
      Handler: !Ref LambdaHandler
      Runtime: !Ref LambdaRuntime
      Role: !GetAtt AlexaSkillIAMRole.Arn
      MemorySize: 512
      Timeout: 60
      Environment:
        Variables:
          Domain: !GetAtt [CloudfrontDistribution, DomainName]
          S3_PERSISTENCE_BUCKET: {Ref: S3UserDataBucket}
  AlexaSkillFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt AlexaSkillFunction.Arn
      Principal: alexa-appkit.amazon.com
      EventSourceToken: !Ref SkillId
  AlexaSkillFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AlexaSkillFunction}
      RetentionInDays: 14
Outputs:
  SkillEndpoint:
    Description: LambdaARN for the regional endpoint
    Value: !GetAtt AlexaSkillFunction.Arn
  WebsiteURL:
    Value: !GetAtt [S3WebAppBucket, WebsiteURL]
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [S3WebAppBucket, DomainName]]]
    Description: Name of S3 bucket to hold website content
  CloudFrontURL:
    Value: !GetAtt [CloudfrontDistribution, DomainName]
    Description: Website cloudfront URL
  AssetsBucketUri:
    Value: !Join ['', ['s3://', !Ref S3WebAppBucket]]
